version: '3.3'
services:

  presidio:
    build:
      context: ./
      dockerfile: Dockerfile
    image: presidio
    container_name: presidio
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    networks:
      - frontend
      - backend
    volumes:
      - ./config:/etc/impact_presidio/
      - ./projects:/srv/projects

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    volumes:
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS_DIR:-./ssl}:/etc/ssl:ro

  safe:
    image: rencinrig/safe-server:1.0.1
    container_name: safe
    restart: on-failure
    ports:
      - ${SAFE_SERVER_PORT:-7777}:7777
    networks:
      - backend
    environment:
      - RIAK_IP=${RIAK_IP:-riak}
      - SLANG_SCRIPT=${SLANG_SCRIPT:-impact/mvp-presidio.slang}
      - AKKA_LOG_LEVEL=${AKKA_LOG_LEVEL:-info}
    volumes:
      - ${SAFE_IMPORTS:-./safe/imports}:/imports
      - ${SAFE_PRINCIPAL_KEYS:-./safe/keys}:/principalkeys

networks:
  frontend:
  backend:
